### PR TITLE
fix(47): markdown updates to unscramble displayed text

### PR DESCRIPTION
**Pull request by Thesephi**
This PR attempts to fix issue #47

### CODE REVIEW

**Comment by guillaumeglaunes** [comment]
Still an issue with getmemelist / get_meme_list, which will probably trouble people completing Chapter 6 of the Near Academy

**Comment by Thesephi** [comment]
Thanks @guillaumeglaunes for the comment. The initial issue #47 only mentioned Chapter 4, but it's a similar fix for Chapter 6 anyways so I decided to bundle it all together. The latest state of this PR includes fixes for both chapters.

**Comment by Thesephi** [comment]
Hi @oceanByte, apologies for tagging you quite abruptly, I'd just wanted to see if this PR could be merged (since it's been created for quite a while) :) It fully addresses the original issue #47 , like so:

# Before
pr-48-before

# After
pr-48-after

It also addresses the same class of issue seen in "Chapter 6" and "Chapter 7" (not mentioned in the original issue #47).

Thank you for your time reviewing & best regards!

**Comment by oceanByte** [comment]
Thank you very much for this PR @Thesephi 
We implemented a redesigned version where these problems should be fixed. This repo is not used anymore that's why I missed your PR. Please check this repo instead: https://github.com/NEAR-Edu/near.academy

**Pull request closed without merging**
